# Generated by Django 5.0.1 on 2024-01-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_blog_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='receiver',
        ),
    ]
